"""empty message

Revision ID: 5bfd3260a3a6
Revises: a040f705ffc4
Create Date: 2020-10-26 07:58:40.985846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfd3260a3a6'
down_revision = 'a040f705ffc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('best_comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'best_comment_id')
    # ### end Alembic commands ###
