"""Integrate the views count column in threads table

Revision ID: 95e66726e2d2
Revises: 042132845203
Create Date: 2020-07-07 09:49:33.333455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e66726e2d2'
down_revision = '042132845203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('views_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'views_count')
    # ### end Alembic commands ###
